Adding a specific mini test that exercises ServerTestUtils.startVoldemortServer. This ~15 line program that simply starts some Voldemort servers using test utils can tickle two different intermittent failures:
(1) ObsoleteVersionException when loading cluster.xml

Testcase: startMultipleVoldemortServers took 0.385 sec
	Caused an ERROR
A successor version version()  to this version() exists for key cluster.xml
voldemort.versioning.ObsoleteVersionException: A successor version version()  to this version() exists for key cluster.xml

and

(2) A bind issue characterized as follows:

Testcase: startMultipleVoldemortServers took 2.066 sec
        Caused an ERROR
java.net.BindException: Address already in use
voldemort.VoldemortException: java.net.BindException: Address already in use
	at voldemort.server.niosocket.NioSocketService.startInner(NioSocketService.java:131)
	at voldemort.server.AbstractService.start(AbstractService.java:62)
	at voldemort.server.VoldemortServer.startInner(VoldemortServer.java:255)
	at voldemort.server.AbstractService.start(AbstractService.java:62)
	at voldemort.ServerTestUtils.startVoldemortServer(ServerTestUtils.java:666)
	at voldemort.utils.ServerTestUtilsTest.setUp(ServerTestUtilsTest.java:50)
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind(Native Method)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:126)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:59)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:52)
	at voldemort.server.niosocket.NioSocketService.startInner(NioSocketService.java:125)