Code compiled on Java8 fails to run on Java6
Ever witnessed
Exception in thread "main" java.lang.NoSuchMethodError:
java.util.concurrent.ConcurrentHashMap.keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView;
	at
voldemort.store.metadata.MetadataStore.updateRoutingStrategies(MetadataStore.java:855)
	at
voldemort.store.metadata.MetadataStore.init(MetadataStore.java:1189)

This is because of the issue documented here
https://gist.github.com/AlainODea/1375759b8720a3f9f094